config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  # get 'home/index'
  get 'home/about'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable
  
  has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not authorized to edit this Friend" if @friend.nil? 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group" style="margin-left: 1%; width: 50%; justify: center; align:center">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class:"form-control", placeholder:"first_name" %>
  </div>

  <div class="field form-group" style="margin-left: 1%; width: 50%; justify: center; align:center">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class:"form-control", placeholder:"last_name" %>
  </div>

  <div class="field form-group" style="margin-left: 1%; width: 50%; justify: center; align:center">
    <%= form.label :email %>
    <%= form.text_field :email, class:"form-control", placeholder:"email" %>
  </div>

  <div class="field form-group" style="margin-left: 1%; width: 50%; justify: center; align:center">
    <%= form.label :phone %>
    <%= form.text_field :phone, class:"form-control", placeholder:"phone" %>
  </div>

  <div class="field form-group" style="margin-left: 1%; width: 50%; justify: center; align:center">
    <%= form.label :twitter %>
    <%= form.text_field :twitter, class:"form-control", placeholder:"twitter" %>
  </div>

  <div class="field form-group" style="margin-left: 1%; width: 50%; justify: center; align:center">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, 
      id: :friend_user_id, 
      class:"form-control", 
      value:current_user.id, 
      type: :hidden 
    %>
  </div>

  <div style="margin-left: 1%; margin-top:23px">
    <%= form.submit class:"btn btn-dark btn-lg" %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>

<%= render 'form', friend: @friend %>

<div class="lead" style="margin-left: 1%; margin-top:23px">
  <%= link_to 'Show', @friend, class:"btn btn-dark" %>
  <%= link_to 'Back', friends_path, class:"btn btn-dark" %>
</div>

app/views/friends/index.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-striped table-bordered table-hover">
  <thead  class="thead-dark">
    <tr>
      <th scope="col">User id</th>
      <th scope="col">First name</th>
      <th scope="col">Last name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Twitter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <td scope="row"><%= friend.user_id %></td>
        <td scope="row"><%= friend.first_name %></td>
        <td scope="row"><%= friend.last_name %></td>
        <td scope="row"><%= friend.email %></td>
        <td scope="row"><%= friend.phone %></td>
        <td scope="row"><%= friend.twitter %></td>
        <td scope="row"><%= link_to 'Show', friend %></td>
        <td scope="row"><%= link_to 'Edit', edit_friend_path(friend) %></td>
        <td scope="row"><%= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friend', new_friend_path, class:"btn btn-dark" %>

app/views/friends/new.html.erb
<h1>Add New Friend</h1>

<%= render 'form', friend: @friend %>


<div style="margin-left: 1%; margin-top:23px">
  <%= link_to 'Back', friends_path, class:"btn btn-dark" %>
</div>

app/views/friends/show.html.erb
<p id="notice"><%= notice %></p>

<div class="jumbotron">
  <h1 class="display-4">
      <%= @friend.first_name %>
      <%= @friend.last_name %>
  </h1>

  <p class="lead">
    <p>
      <strong>Email:</strong>
      <%= @friend.email %>
    </p>

    <p>
      <strong>Phone:</strong>
      <%= @friend.phone %>
    </p>

    <p>
      <strong>Twitter:</strong>
      <%= @friend.twitter %>
    </p>
  </p>

  <hr class="my-4">
  <p class="lead">
    <%= link_to 'Edit', edit_friend_path(@friend), class:"btn btn-dark" %>
    <%= link_to 'Back', friends_path, class:"btn btn-dark" %>
  </p>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%# <a class="navbar-brand" href="#">Friend</a> %>
  <%= link_to 'Friends App', root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'About Us', home_about_path, class:"nav-link" %>
        </li>
      
        <li class="nav-item">
          <%= link_to 'Friends', friends_path, class:"nav-link" %>
        </li>
      
        <li class="nav-item">
          <%= link_to 'Add Friend', new_friend_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link" %>
        </li>
      
        <li class="nav-item">
          <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>
      <% else %>

        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path, class:"nav-link" %>
        </li>

      <% end %>

    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About</h1>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<h1>This is my test with ruby</h1>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <title>Friends</title>

    <!-- Required meta tags -->
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>

    <div >
      <%= render "home/header" %>
      <%= yield %>
    </div>
  

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>